### PR TITLE
Update prgenv.md with link to HPE Cray docs

### PR DESCRIPTION
**Pull request by hdrei**
Include link to https://cpe.ext.hpe.com/docs/

### CODE REVIEW

**Review by Chroxvi — APPROVED** [review]
I wonder if we should include more links to the HPE/Cray docs in the LUMI docs, e.g.

- Link to https://cpe.ext.hpe.com/docs/#hpe-cray-compiling-environment from https://docs.lumi-supercomputer.eu/development/compiling/cce/
- Link to https://cpe.ext.hpe.com/docs/#hpe-cray-scientific-and-math-libraries from https://docs.lumi-supercomputer.eu/development/libraries/cray-libraries/
- Link to https://cpe.ext.hpe.com/docs/#hpe-cray-user-environment from https://docs.lumi-supercomputer.eu/runjobs/lumi_env/softwarestacks/#crayenv (and possibly, other parts of the LUMI docs as well)
- Link to https://cpe.ext.hpe.com/docs/#debugging-tools from https://docs.lumi-supercomputer.eu/development/debugging/gdb4hpc/, https://docs.lumi-supercomputer.eu/development/debugging/valgrind4hpc/, and https://docs.lumi-supercomputer.eu/development/debugging/stat-atp/
- Link to https://cpe.ext.hpe.com/docs/#profiling-and-performance-optimization-tools from https://docs.lumi-supercomputer.eu/development/profiling/perftools/

What do you think? There is always the risk of ending up with dead links if the HPE/Cray docs change...

**Comment by hdrei** [comment]
> I wonder if we should include more links to the HPE/Cray docs in the LUMI docs, e.g.
> 
>     * Link to https://cpe.ext.hpe.com/docs/#hpe-cray-compiling-environment from https://docs.lumi-supercomputer.eu/development/compiling/cce/
> 
>     * Link to https://cpe.ext.hpe.com/docs/#hpe-cray-scientific-and-math-libraries from https://docs.lumi-supercomputer.eu/development/libraries/cray-libraries/
> 
>     * Link to https://cpe.ext.hpe.com/docs/#hpe-cray-user-environment from https://docs.lumi-supercomputer.eu/runjobs/lumi_env/softwarestacks/#crayenv (and possibly, other parts of the LUMI docs as well)
> 
>     * Link to https://cpe.ext.hpe.com/docs/#debugging-tools from https://docs.lumi-supercomputer.eu/development/debugging/gdb4hpc/, https://docs.lumi-supercomputer.eu/development/debugging/valgrind4hpc/, and https://docs.lumi-supercomputer.eu/development/debugging/stat-atp/
> 
>     * Link to https://cpe.ext.hpe.com/docs/#profiling-and-performance-optimization-tools from https://docs.lumi-supercomputer.eu/development/profiling/perftools/
> 
> 
> What do you think? There is always the risk of ending up with dead links if the HPE/Cray docs change...

Will add these links

**Comment by hdrei** [comment]
> > I wonder if we should include more links to the HPE/Cray docs in the LUMI docs, e.g.
> > ```
> > * Link to https://cpe.ext.hpe.com/docs/#hpe-cray-compiling-environment from https://docs.lumi-supercomputer.eu/development/compiling/cce/
> > 
> > * Link to https://cpe.ext.hpe.com/docs/#hpe-cray-scientific-and-math-libraries from https://docs.lumi-supercomputer.eu/development/libraries/cray-libraries/
> > 
> > * Link to https://cpe.ext.hpe.com/docs/#hpe-cray-user-environment from https://docs.lumi-supercomputer.eu/runjobs/lumi_env/softwarestacks/#crayenv (and possibly, other parts of the LUMI docs as well)
> > 
> > * Link to https://cpe.ext.hpe.com/docs/#debugging-tools from https://docs.lumi-supercomputer.eu/development/debugging/gdb4hpc/, https://docs.lumi-supercomputer.eu/development/debugging/valgrind4hpc/, and https://docs.lumi-supercomputer.eu/development/debugging/stat-atp/
> > 
> > * Link to https://cpe.ext.hpe.com/docs/#profiling-and-performance-optimization-tools from https://docs.lumi-supercomputer.eu/development/profiling/perftools/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do you think? There is always the risk of ending up with dead links if the HPE/Cray docs change...
> 
> Will add these links

Yes, there is a risk that the links will be broken in time. But I think that the extra value that is got by more people ending up to the Cray docs pages is bigger than the fear for broken links. (And broken links there will be always - I just fixed one while adding these links)

**Review by Chroxvi — APPROVED** [review]
If I remember correctly, we have an automatic check for broken links when the docs are built (at least I hope we do), so we should get notified if things break.

I think this is ready for merge.

**Pull request merged**
