### PR TITLE
Add notes column

### PR DESCRIPTION
**Pull request by Danzelot**

### CODE REVIEW

**Comment by Danzelot** [comment]
I accidentally used a "ø" in the branch name. I hope it still works.

**Comment by Danzelot** [comment]
Please suggest changes if you don't like something.

**Comment by klust** [comment]
I actually can't get it to work. Can't get the git branch in my terminal, and the preview service for the documentation also breaks down because of the ø.

**Comment by olouant** [comment]
I renamed the branch to `jorn/slurm-partition` which had the side effect of closing this PR. I created a new one with the new branch.

**Pull request closed without merging**
