### PR TITLE
WIP: Adds basic documentation on wrapper tool

### PR DESCRIPTION
**Pull request by Nortamo**
PR should be merged after tool has been installed on LUMI.
Before merging, make sure that the documented module name matches the installed one. 
Closing #21 as that one was from the wrong branch  

## Content
    - Document how container wrapper tools works (Tykky)
    - Adds new subcategory under computing
    - Adds Tykky documentation to navigation

### CODE REVIEW

**Review by Chroxvi — CHANGES_REQUESTED** [review]
I think this now contains all the relevant content - only the final polishing is needed. As part of this _somebody_ should probably consider consistency with the rest of the documentation, e.g.
- Does this adhere to any spelling conventions for LUMI docs?
- Does this adhere to any formatting conventions for LUMI docs (including formatting of code examples)?

**Review by Chroxvi — APPROVED** [review]

**Comment by Chroxvi** [comment]
I think this is ready to be merged once Tykky has been installed on LUMI. @mszpindler did you manage to create an easybuild recipe for this and install it on LUMI?

**Comment by mszpindler** [comment]
There is already PR (https://github.com/Lumi-supercomputer/LUMI-EasyBuild-contrib/pull/5) for this. I still need rename the recipe.

**Comment by Nortamo** [comment]
Based on discussion we changed the name to be more descriptive in the documentation.

**Pull request merged**
