### PR TITLE
Add general Singularity docs

### PR DESCRIPTION
**Pull request by rsarm**
I move this old pr to here https://github.com/Lumi-supercomputer/Containers/pull/7

### CODE REVIEW

**Comment by rsarm** [comment]
Converted it to draft as the `singularity-lumi/<version>-mpi` module is still pending.

**Comment by trz42** [comment]
Did some spell checking and formatting on singularity.md

**Comment by rsarm** [comment]
@trz42 I ran some tests with rocm containers with singularity. It looks that there's no need for `--rocm`. I think I had seen the same thing on the grenoble nodes.

**Comment by abdulrahmanazab** [comment]
> @trz42 I ran some tests with rocm containers with singularity. It looks that there's no need for `--rocm`. I think I had seen the same thing on the grenoble nodes.

Yes, if you have all the libraries installed on the container and the device entries. In this case its only use is just to double check that everything is ok. Still useful I think

**Comment by rsarm** [comment]
@olouant this is ready. Could you have a look and if you agree merge it?

**Review by olouant — APPROVED** [review]

**Pull request merged**
