### PR TITLE
Adaptations to the EasyBuild documentation for the installation of co…

### PR DESCRIPTION
**Pull request by klust**
…ntainer modules.

### CODE REVIEW

**Comment by klust** [comment]
Draft as it needs to be verified on the system, and the software is also not yet available on the system. The text was written during LUMI downtime.

**Comment by Danzelot** [comment]
Sounds very good. 
What is the status? Are there any container modules already available? I can't see them in the SW library.

**Comment by klust** [comment]
Beta-version of the modules will roll out with the 23.09 software stack with PyTorch as an example. But a lot of testing is needed with the new containers to improve the documentation on how to use them so AI experts are needed to work on that.

**Comment by klust** [comment]
I'm ready to put the matching documentation in the LUMI Software Guide on the web, and the containers are also on the system, so this can be merged.

**Review by olouant — APPROVED** [review]

**Pull request merged**
